#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qpid-python
Version  : 1.37.0
Release  : 19
URL      : https://mirrors.ocf.berkeley.edu/apache/qpid/python/1.37.0/qpid-python-1.37.0.tar.gz
Source0  : https://mirrors.ocf.berkeley.edu/apache/qpid/python/1.37.0/qpid-python-1.37.0.tar.gz
Summary  : Python client implementation and AMQP conformance tests for Apache Qpid
Group    : Development/Tools
License  : Apache-2.0
Requires: qpid-python-bin = %{version}-%{release}
Requires: qpid-python-license = %{version}-%{release}
Requires: qpid-python-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
Patch1: 0001-Remove-tabs.patch

%description
# Qpid Python
This distribution contains a Python client implementation and AMQP
conformance tests for Apache Qpid.

%package bin
Summary: bin components for the qpid-python package.
Group: Binaries
Requires: qpid-python-license = %{version}-%{release}

%description bin
bin components for the qpid-python package.


%package legacypython
Summary: legacypython components for the qpid-python package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the qpid-python package.


%package license
Summary: license components for the qpid-python package.
Group: Default

%description license
license components for the qpid-python package.


%package python
Summary: python components for the qpid-python package.
Group: Default

%description python
python components for the qpid-python package.


%prep
%setup -q -n qpid-python-1.37.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1545529507
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qpid-python
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/qpid-python/LICENSE.txt
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/qpid-python-test
/usr/bin/qpid-python-test.bat

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qpid-python/LICENSE.txt

%files python
%defattr(-,root,root,-)
